### ISSUE TITLE
Разбиение кода на модули

### ISSUE THREAD

**Issue by arsenier** [SPBUnited/strategy#15]

**Comment by yarmolinskiyam** [comment]
- python_controller.py -> ssl_parse.py
- strategy/
	- strategy.py
	- defence.py
	- attack.py
- router/
	- router.py
	- route.py
	- waypoint.py
- robot_ctrl/
	- robot_controller.py
	- robot.py
- robot_command_sink/
	- robot_command_sink.py
- aux/
	- aux.py
	- quickhull.py
	- field.py
	- signal.py
	- tau.py
	- entity.py
	- const.py
